# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Data Transfer Initiative

# NOTE: If replacing this next line with your own URL, you likely want "https://" not "http://"
production_url : https://dtinit.github.io/data-transfer-initiative

# Tell Github to use the kramdown markdown interpreter
# (see https://help.github.com/articles/migrating-your-pages-site-from-maruku)
markdown: kramdown

collections:
  posts:
    layout: post
    output: true
    permalink: /blog/:year/:month/:day/:title

plugins:
  - jekyll-feed